---
title: "Covid 19 Analysis"
author: "Your name goes here"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure sizes
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```


```{r load-libraries, include=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(mosaic)
library(ggthemes)
library(lubridate)
library(here)
library(skimr)
library(janitor)
library(httr)
library(readxl)
library(vroom)
```

# CDC COVID-19 Public Use Data

```{r, cache=TRUE}
# file contains 11 variables and 3.66m rows and is well over 380Mb. 
# It will take time to download

# URL link to CDC to download data
url <- "https://data.cdc.gov/api/views/vbim-akqf/rows.csv?accessType=DOWNLOAD"

covid_data <- vroom::vroom(url)%>% # If vroom::vroom(url) doesn't work, use read_csv(url)
  clean_names()


```

Given the data we have, I will produce two graphs that show death % rate:

1. by age group, sex, and whether the patient had co-morbidities or not
1. by age group, sex, and whether the patient was admited to Intensive Care Unit (ICU) or not.


```{r}
skim (covid_data)
```
By Age group, sex, and morbidity
``` {r}
covid_data_clean_1 <- covid_data %>% 
filter(death_yn!="Missing") %>% 
  filter(death_yn!="Unknown") %>% 
  filter(age_group!="Unknown") %>% 
  filter(sex!="Unknown") %>%
  filter(sex!="Missing") %>% 
  filter(medcond_yn!="Missing") %>%
  filter(medcond_yn!="Unknown") %>%
  filter(sex!="Other")
```

```{r}
         
covid_morb<- covid_data_clean_1 %>% 
  group_by(age_group,death_yn,sex,medcond_yn) %>%
  summarise(count=n()) %>% 
  pivot_wider(names_from = death_yn, values_from = count) %>% 
  mutate(death_rate=(Yes/(Yes+No))) %>% 
  mutate(death_rate_perc=paste(round(100*death_rate, 1), "%", sep=""))

covid_morb

covid_morb$medcond_yn_f = factor(covid_morb$medcond_yn, levels=c('Yes','No'))

morb.labs <- c("Without comorbidities", "With comorbidities")
names(morb.labs) <- c(medcond_yn_f="No", medcond_yn_f="Yes")

ggplot(covid_morb, aes(x=death_rate,y=age_group))+
  geom_col(alpha=0.8,fill="#6C7EA2")+
  facet_grid(medcond_yn_f~sex, 
               ,labeller=labeller(medcond_yn_f=morb.labs))+
  labs(title="Covid death rate by age group, sex and presence of co-morbidities",x="",y="")+
  scale_x_continuous(labels=scales::percent)+
  geom_text(aes(label=death_rate_perc),nudge_x = 0.07, size=3)+
  coord_fixed(ratio = 0.04)+
   theme(strip.background = element_rect(
     color="black", fill="grey", linetype="solid"), panel.background = element_rect(fill = "white"),panel.grid=element_line(size=0.5, colour="#F1F1EB"), panel.border = element_rect(fill=NA))
```
By age group, sex and admissions to ICU 

``` {r}
covid_data_clean_2 <- covid_data %>% 
  filter(death_yn!="Missing") %>% 
  filter(death_yn!="Unknown") %>% 
  filter(age_group!="Unknown") %>% 
  filter(sex!="Unknown") %>%
  filter(sex!="Missing") %>% 
  filter(icu_yn!="Missing") %>%
  filter(icu_yn!="Unknown") %>%
  filter(medcond_yn!="Missing") %>%
  filter(medcond_yn!="Unknown") %>%
  filter(sex!="Other")
         
covid_icu<- covid_data_clean_2 %>% 
  group_by(age_group,death_yn,sex,icu_yn) %>%
  summarise(count=n()) %>% 
  pivot_wider(names_from = death_yn, values_from = count) %>% 
  mutate(death_rate=(Yes/(Yes+No))) %>% 
  mutate(death_rate_perc=paste(round(100*death_rate, 1), "%", sep=""))

covid_icu

covid_icu$icu_yn_f = factor(covid_icu$icu_yn, levels=c('Yes','No'))

icu.labs <- c("Not Admitted to ICU", "Admitted to ICU")
names(icu.labs) <- c(icu_yn_f="No", icu_yn_f="Yes")

ggplot(covid_icu, aes(x=death_rate,y=age_group))+
  geom_col(alpha=0.8,fill="#FF5B33")+
  facet_grid(icu_yn_f~sex, 
               , labeller=labeller(icu_yn_f=icu.labs))+
  labs(title="Covid death rate by gender, age and ICU admittance",x="",y="")+
  scale_x_continuous(labels=scales::percent)+
  geom_text(aes(label=death_rate_perc),nudge_x = 0.07, size=3)+
  coord_fixed(ratio = 0.04)+
  theme(strip.background = element_rect(
     color="black", fill="grey", linetype="solid"), panel.background = element_rect(fill = "white"),panel.grid=element_line(size=0.5, colour="#F1F1EB"), panel.border = element_rect(fill=NA))
```



